version: '3'
services:
    admin_agent:
        #build: ./
        container_name: admin_agent
        # command: uvicorn app.main_admin:app --reload --workers 1 --host 0.0.0.0 --port 8000
        image: docker.pkg.github.com/5gzorro/identity/5g-zorro-teste-agent_issuer:1.0.0
        ports:
            - "6200:8000"
        expose:
            - "6200"
        restart: always
        env_file:
            - .env
        depends_on:
            - mongodb_container

    trading_provider_agent:
        container_name: trading_provider_agent
        image: docker.pkg.github.com/5gzorro/identity/5g-zorro-teste-agent_holder:1.0.0
        ports:
            - "6800:8000"
        expose:
            - "6800"
        restart: always
        env_file:
            - .env
        depends_on:
        #    - mongodb_trade_provider_container
            - mongodb_container

    mongodb_container:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db

    #mongodb_trade_provider_container:
    #    image: mongo:latest
    #    ports:
    #        - 27018:27017
    #    volumes:
    #        - mongodb_data_container:/data/db_provider

volumes:
    mongodb_data_container: