version: '3'
services: 
    admin_operator_a_agent:
        build: ./
        container_name: admin_operator_a_agent
        #networks:
        #    front:
        #        ipv4_address: 172.220.18.0
        command: uvicorn app.main_admin:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-level error
        ports:
            - "6200:8000"
        #restart: always
        volumes:
            - "./app/logs:/usr/src/app/logs"
        env_file:
            - .env_admin
        depends_on:
            - mongodb_operator_a_container
    
    trader_operator_b_agent:
        build: ./
        container_name: trader_operator_b_agent
        command: uvicorn app.main_trading_provider:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-level error
        ports:
            - "6800:8000"
        volumes:
            - "./app/logs:/usr/src/app/logs"
        env_file:
            - .env
        depends_on:
            - mongodb_operator_b_container

    trader_operator_c_agent:
        build: ./
        container_name: trader_operator_c_agent
        command: uvicorn app.main_trading_provider:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-level error
        ports:
            - "6600:8000"
        volumes:
            - "./app/logs:/usr/src/app/logs"
        env_file:
            - .env_2
        depends_on:
            - mongodb_operator_c_container

    regulator_a_agent:
        build: ./
        container_name: regulator_a_agent
        command: uvicorn app.main_regulator:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-level error
        ports:
            - "6300:8000"
        volumes:
            - "./app/logs:/usr/src/app/logs"
        env_file:
            - .env_regulator
        depends_on:
            - mongodb_regulator_a_container


    mongodb_operator_a_container:
        image: mongo:latest
        #environment:
        #    MONGO_INITDB_ROOT_USERNAME: root
        #    MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
            - 27017:27017
        volumes:
            - mongodb_operator_a_data_container:/data/db

    mongodb_operator_b_container:
        image: mongo:latest
        ports:
            - 27018:27017
        volumes:
            - mongodb_operator_b_data_container:/data/db

    mongodb_operator_c_container:
        image: mongo:latest
        ports:
            - 27020:27017
        volumes:
            - mongodb_operator_c_data_container:/data/db

    mongodb_regulator_a_container:
        image: mongo:latest
        ports:
            - 27019:27017
        volumes:
            - mongodb_regulator_a_data_container:/data/db

volumes:
    mongodb_operator_a_data_container:
    mongodb_operator_b_data_container:
    mongodb_operator_c_data_container:
    mongodb_regulator_a_data_container:
    
        
#networks:
#  front:
#    external:
#      name: multi-host-network